### ISSUE TITLE
我使用node.js写了一个同样功能的脚本

### ISSUE THREAD

**Issue by FastLight126** [FW27623/qqwry#1]
不过中间过程是直接 setup /verysilent /dir=xxx 安装的，安装后把 qqwry.dat 复制出来之后 unins000 /verysilent 卸载

**Comment by FW27623** [comment]
也挺好的，实现方式多种，主要还是要从公众号抓链接，不然后面都无法实现

**Comment by FastLight126** [comment]
之前没有发现innoextract这个东东，现在知道有这个了，我去改造一下。

**Comment by FW27623** [comment]
> 之前没有发现innoextract这个东东，现在知道有这个了，我去改造一下。

可以的，我也是偶然发现，能实现功能就行，整这个就是方便自己更新库用的
