### ISSUE TITLE
最近更新后 我运行出错了

### ISSUE THREAD

**Issue by vonaxs** [FW27623/qqwry#15]
大佬好：

几个月前我按照你的教程操作。运行成功。
但是最近你更新了一些代码后，我的代码也同步更新了，但是我这边运行就失败了。
但是我看你这边运行都是成功的。

求大佬看看。
运行错误的图片如下：

![屏幕截图 2024-08-08 180110](https://github.com/user-attachments/assets/82728aa7-e289-464b-b56f-5f557bfa19e7)

**Comment by FW27623** [comment]
一直没更新README，官方现在已经停止公众号的更新了，现在获取的话得先获取官方的授权，获得对应链接才能够下载的。

**Comment by FW27623** [comment]
> > 一直没更新README，官方现在已经停止公众号的更新了，现在获取的话得先获取官方的授权，获得对应链接才能够下载的。
> 
> 请问楼主是怎么获取授权的？
可查看官网申请方式：https://cz88.net/geo-public
