### ISSUE TITLE
我使用PHP写了一个同样功能的脚本

### ISSUE THREAD

**Issue by xuduorg** [FW27623/qqwry#9]
1.看见下面用nodejs写的相同功能，我也回复一下。我使用PHP写了一个同样功能的脚本，正好在找如何从安装包里提取，也正好找到innoextract，但是我觉得麻烦了，想看看有没有php就可以的。
2.不得不说您的代码写的真的不错，我还是写的那种直接从公众号里，他发文章的合集里抓取最新的文章链接，再从这个链接里再正则匹配下载地址，耗时都得好几秒，而且我还没屏蔽预告之内的。
3.你的这个项目会一直更新吗？如果一直更新我就直接自动拉取你的文件了。用php写真的不太适合，很慢。
最后再感谢你开源，谢谢！

**Comment by FW27623** [comment]
哈哈，我是业余的，这个项目目前趋于稳定，稳定运行了也有蛮久，只要没出什么搞不定的问题，会一直维护
